### ISSUE TITLE
Segfault on Ubuntu 18.04 x64

### ISSUE THREAD

**Issue by billotronic** [blockpool-io/BPL-node#74]
Manual install of all dependencies gave no errors or hints of trouble. 

Regular log output: 

https://pastebin.com/7QgrJgj9

and output from segfault-handler:

https://pastebin.com/nVYSej2E

**Comment by cyrus19901** [comment]
What version of node are you using ? If updated to the latest and still facing issues, can you please delete node_modules and run npm install again to see if that fixes it ?

**Comment by billotronic** [comment]
Node :: 6.9.5
npm :: 3.10.10

and if it would help, all installed package versions :: https://pastebin.com/Jg0uDWH1

I will try with current versions right now to see if that makes a difference

**Comment by billotronic** [comment]
Well that took care of that. It is now working with these versions:
Node :: 8.10.0
npm :: 3.5.2

What is strange is the difference in npm versions. The only thing done differently was not using n to switch to 6.9.5. I have no explanation for the older version being used for npm.

**Comment by cyrus19901** [comment]
Yes the node version is a crucial component. Glad you got it working . Closing the ticket now.
